### ISSUE TITLE
If 404 is received on a javascript path

### ISSUE THREAD

**Issue by benschwarz** [juliocesar/rack-pagespeed#7] opened 2011-01-20 04:23 UTC
I get an error of 

`undefined method`stat' for nil:NilClass` from rack-level.
I knew what it was straight away, others might not though.

**Comment by juliocesar** [comment] 2011-01-20 05:14
As in when you delete a bundle of JS? When I test that here, I just get 404 without errors (which is what should happen).

If you could send me the full stacktrace, that would be nice. I'm guessing this has something to do with a filter not finding a file and calling File#stat on nil, rather than it happening on a 404 caused by an asset that doesn't exist.

Also, please make sure you're on 1.0.2. I've fixed a few bugs on it and I think this one's in.

**Comment by benschwarz** [comment] 2011-01-20 05:15
Yes, your description is better, it doesn't 404—it fails in filterland. 
I'll verify it with 1.0.2…

**Comment by juliocesar** [comment] 2011-01-21 02:18
Ok I'll close this as I'm positive it got fixed on 1.0.2. Let me know if you prove me wrong and I'll reopen.

**Closed as completed by juliocesar** 2011-01-21 02:18 UTC
