### ISSUE TITLE
Wrong number of arguments in configuration exception

### ISSUE THREAD

**Issue by benschwarz** [juliocesar/rack-pagespeed#5] opened 2011-01-19 11:12 UTC
I used your example in a new rails application, only I dropped it into an initialiser: (using 1.9 hash syntax)

<pre>
Rails.application.config.middleware.use Rack::PageSpeed, public: Rails.public_path do
  store disk: Dir.tmpdir
  inline_javascript max_size: 4000
  inline_css
  combine_javascripts
end
</pre>

I get:

`/Users/ben/.rvm/gems/ruby-1.9.2-p0@secret/gems/rack-pagespeed-1.0.0/lib/rack/pagespeed/config.rb:34:in`method_missing': wrong number of arguments (2 for 1) (ArgumentError)`

**Comment by juliocesar** [comment] 2011-01-19 11:49
Mr Ben! Let me give that a shot and I'll come back to you. Thanks for the report.

**Comment by juliocesar** [comment] 2011-01-19 12:19
I'll keep it open as a bug, since you should be getting a NoSuchFilter error rather than that, but the problem is you misspelt "inline_javascripts" when calling that filter.

Also, this filter needs more robust URL parsing. Right now the filter is looking for JavaScripts ending with ".js". So in Rails' case, the timestamp it adds makes the filter skip it. That's bad.

Anyway, give it a go as `inline_javascripts max_size: 4000` and it'll work. Tested with Ruby 1.9.2-p0, Rails 3.0.3.

**Comment by benschwarz** [comment] 2011-01-19 12:23
Argh, that's what I get for using 1.9 syntax!
It totally should throw an error though, as I had no idea what was happening. 

I was rather confused because it seemed to be the configuration arguments that were erroring. Boo.

**Comment by juliocesar** [comment] 2011-01-19 22:37
Closed by 76874d761a33ac43d221fecc37f2f18a519a7f0f, properly testing NoSuchFilter

**Comment by juliocesar** [comment] 2011-01-19 22:37
Ok, fixed! It'll properly raise NoSuchFilter now. Thanks again.

**Closed as completed** 2011-01-20 06:37 UTC
